// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesToDoList.Models;

namespace RazorPagesToDoList.Migrations
{
    [DbContext(typeof(RazorPagesToDoListContext))]
    partial class RazorPagesToDoListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorPagesToDoList.Models.ToDoNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Done");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("DutyHolder");

                    b.Property<bool>("InProgress");

                    b.Property<string>("Priority");

                    b.Property<string>("TaskDescription");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("ToDoNote");
                });
#pragma warning restore 612, 618
        }
    }
}
